pipeline:
  - workflow.filter.put:
      resourceName: Task
      name: All t535 Tasks
      query:
        assignee: $uri:current-user
      properties:
        pipeforce_sql: |
          -- Content-Type: application/json
          SELECT
            json_build_object('id', id_, 'name', name_, 'assignee', assignee_, 'processInstanceId', 
            proc_inst_id_, 'processDefinitionId', proc_def_id_, 'description', description_, 
            'taskDefinitionKey', task_def_key_, 'owner', owner_, 'delegation', delegation_, 
            'prioritiy', priority_, 'created', create_time_, 'due', due_date_, 'followUp', follow_up_date_, 
            'suspended', suspension_state_, 'tenantId', tenant_id_)
          FROM
            ACT_RU_TASK
          WHERE
            name_ LIKE :quickSearch AND assignee_ = :assignee
          ORDER BY
            create_time_
          LIMIT :maxParam OFFSET :offsetParam ;